name: LightningSticks
version: ${project.version}
main: lightningsticks.me.buryings.lightningSticks
authors: [ "Buryings", "hypews" ]
description: A lightning sticks plugin
commands:
  lsgive:
    description: Gives people lightning sticks
    aliases:
      - lightningstickgive
      - givels
      - lsg