name: Lightning Sticks
version: ${project.version}
main: lightningsticks.me.buryings.lightningsticks.me.buryings.lightningSticks
authors: [ Buryings ]
description: Lightningsticks
commands:
  lsgive:
    description: Gives people lightning sticks