name: LightningSticks
version: ${project.version}
main: me.buryings.lightningsticks.LightningSticks
authors: [ "Buryings" ]
description: A lightning sticks plugin
commands:
  lsgive:
    description: Gives people lightning sticks
    aliases:
      - lightningstickgive
      - givels
      - lsg
  lsremove:
    description: Removes peoples lightning sticks
    aliasses:
      - lightningstickremove
      - removels
      - lsr